language: go

go:
  - 1.4

env:
  - GIMME_OS=linux GIMME_ARCH=arm

install:
    - go get -d -v ./...

script:
    - go install -v ./...

deploy:
  provider: s3
  access_key_id:
    secure: Nz+2EYZ0s2w1tXGZdHYzeO6ydRbcZiIP+IgkVrrkRRrdIGn15VC6LIg0qcjc4v7C4jkb2gVrmCLwsjyCETwCFLwHEK0SFXXK1LN9OCUTALxmvfHsk7iVLnL5qKz9MnaSho/U/CvnxGWV5J38Yg7YDabqD2X5j7fRKV5D5P21cb/GNWmCQPAbAcdM3JFhQTBpk4I4nCu1kh2I4x6HfzLM9vKKDW40srOQGYuFDtlolYiPMYjmtstPGbcLH/UyFHkoMMy1EzbSTYGcuyDIknS1TfWhLTzwKxBvv+i6jgaq46QLOCstLghoKwJhqGRWqhOFezNzRJVc+y18/lIF8CU0sW1di8UBAMpPk0ZOjY/DWrsWCXmiPBzy5WxQb+WG51dm27GEDM+qFor4elvBLbTVaaNXpY5d8ksUGU8N2iB2Zb6CaD/URoDSAh4nOnbx+Tkw3gkhCg8lgghBP3pgD6HnK1g2zyaVe9kXgn67L//8RKKJKApQnKDeiA8PJcN6FDGBeOpFrx0A5qas7mBdLGy2ohMytqkjYZWb/zKOtt2YZwO7PRel5Q/Eu5mXSO0oGRUBuuhJxJbReYd1IdeuEkimfS0aoQ6YiTa1+abrRMEjRuKNMkPk+ZMBYZhVMAbSGfg0Ys2j/W/knNl7fziawwO/lF7TpUTP8NCkttvbhz8SM+Y=
  secret_access_key:
    secure: hjqTr3LS+4xvZj16B7BQUF9m3Fd7DrLfvfMo86xnGc7uNXWXvMVXts1RhDd9evHhzd3In8LBr8iRCRtUh1PaJY8K2bHO9K9Voht/SdEKwIdczBqYmlXEOR4fmO4W/KtMPt3Nu90CFCO9DgTDPmGRz9GlqIfpWcVAtQ+emGDgY6I/Em9pSpIcfluKp/1nA0jmkbzR6lfhBy6Ae+T9s60cI4CUzQN5o5YuCEJ3zJUCBNKs5xjXAJJ1rXiV3aaazwmvPvBKWXoG5L8N5caauwOlEJwmg4l1XMZxuj3EHPzUI04EffyzgkVFGnXt37j5lHoyCSdPwJH4zM1jufqOzFYthn7bfYg3KWLI/j7liJxSwqanepRgGeWCBMrLl40vMOIWelc5n2usbQZZumtohC+CMXOuFcEzBva+DqeP8irINQuGXgBC9ofFZ8jWye4yMQFIdyCDoVD6P8v9R37TsKOeCfNchhX12PzVOQMLEAZrLUXzk/M34KFrkj53Ll8YCA7s5xq2pJQ9/jvgSzIGqeI0aMUZiHtfXJWaUz+qzJTAxxhnRlBe7g0LHspEhrl73AFEfepQt/650vIvTvlqHltsmAF3IepusmqP3syVLCd1A7O/SyyEtDhMIqYDnoqVT3itBg3v51W15cFBBwUQu3xaY+fOoQ1pcvGEvpKXwdwCBuY=
  bucket:
    secure: HsDxDJ3/RHa7Qi9036U7730s9NwrTA2kw0euDI7qPoBz9+Qlw5YzFBgatFGm6KBqULWwQAaVtQBZr6XM60+nc/pICE47zwpNFM11nWKV87ScKt7uxfPVgxYJNohdUNso8qN0kx2nm1794m1XS1btleElQt9hS1gkipsl8u8IoSYeZFedi8u++d9kOiTUDX4uD2vxC4OdJaBFnpqxezlf7q5RmfF5hruuPGIgDyMKoAOPLn3g6/HPybplPEnQKf7obJ6fr4SU4cg+Z3jN2QWD7nikquinXmVzd0PbhE0Q+sSDXPXjCIjtTSX1vpKAlXTOkWmA2qpYRjV3/7iU2yzTQA9uufId591J8EWh366kTJsoQhYJXuY9jEPupKDV71933SWc452rO+TckkmphLNW7i9lUT5fSICsvYdob2JjoHjYJlFnr7Ukh7vva2L0WHVfP/GCOht6nvJHEzwz8WqZbfuZHeoN5BAuEdP+x6fx836e/2CF1TAsOYBIKMexpOV9BiCJ6xerIOF0/nz0WyO76v4PZWYT0eSYyg93BpeyS1ykuCNghwb1wFicjtxzk2qPeaWfOMjnFTbMloEtk18CA1zJ82JuQ1OjCXDLQ4HXsQjL/KO33WH6uLaeGROuZiML0TKuvxViKUaMamlD+gQZzSzJRV1NN0XmfFNaBMRRIvI=
  region:
    secure: kYso/td1n2f85dTSnUvNw5Uzi8rv5Ojdy7FrBkAJpUBzC3JNIrFH8+htvSfz5fofuRAy6CAvpemFcp/X2oDBIZ97hbQTHFLqD5m2F99DvihW/JRxsuDAQ8uYWn8IFIAg7yER9wZyX71DflDqmqd/rvKWon1/JcpV65oW31RtjkXXQFsmGKR8WtukLedx2HcFG9OqgbEcj90WLs5q7uCbDkrc2VLlB3INcHrLeCjfhfXypbv4mjGiX4Z2gqzJW+jz7VbMZFkf6OLSH4sNg5tJbR77OIWdC9EYYNK8TLszWr20f54cggL6ZMtPjoyBEqw1AOx4fDTs0WbDjfvMxJHTlGw+TXZxQ1TztCLvK4RQk+Rf3EcmVP88lEfA63nK50/jByW+Gv0PWl19r7ktU6W3UHKYgg+nFGF6TzWoqbNSdBiFLfX+1go/ttvc5ECLCduykiDR2oBuAXabjNBwNVERnUFDdfPI3kCN/nkFcHzFFlY7QTTVYWWigY1K9NkSmgp8qIESNpJNJGd7KdkYJxhVcLLg2XnhOt3DObQDohRxZfJ/veElHcnkyqo4b9qha8ZIYKCJZrNmWIlXY7TmHr4vO5m65Y30e74uBMekvWOqMgnFf/5YD1xJNYVx46MTOwPLblUDx6re8zRwcSZnFBmHK6LwWog9wF7L1dHlSw15G3o=
  local_dir: "$HOME/gopath/bin"
  skip_cleanup: true